sas/booking/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import new_booking
from .views import NewBooking
from .views import search_booking
from .views import SearchBookingQueryView
from .views import search_booking_table
from .views import confirm_booking
from .views import cancel_booking
from .views import delete_booking
from .views import delete_booktime
from .views import all_bookings
from .views import pending_bookings
from .views import approve_booking
from .views import deny_booking
from .views import show_booktimes
from .views import booking_details
from .views import tagged_bookings

urlpatterns = [
    url(r'^newbooking/$',
        new_booking, name='newbooking'),
    url(r'^newbooking2/$',
        NewBooking.as_view(), name='newbooking2'),
    url(r'^searchbooking/$',
        search_booking, name='searchbooking'),
    url(r'^confirmbooking/(\d+)$',
        confirm_booking, name='confirmbooking'),
    url(r'^cancelbooking/(\d+)$',
        cancel_booking, name='cancelbooking'),
    url(r'^searchbookingquery/$',
        SearchBookingQueryView.as_view(),
        name='searchbookingquery'),
    url(r'^searchbookingg/$',
        SearchBookingQueryView.as_view(), name='searchbookingtable'),
    url(r'^deletebooking/(\d+)$',
        delete_booking, name='deletebooking'),
    url(r'^approvebooking/(\d+)$',
        approve_booking, name='approvebooking'),
    url(r'^denybooking/(\d+)$',
        deny_booking, name='denybooking'),
    url(r'^taggedbookings/(\d+)$',
        tagged_bookings, name='taggedbookings'),
    url(r'^bookingdetails/(\d+)$',
        booking_details, name='bookingdetails'),
    url(r'^deletebooktime/(\d+)/(\d+)$',
        delete_booktime, name='deletebooktime'),
    url(r'^allbookings/$',
        all_bookings, name='allbookings'),
    url(r'^pendingbookings/$',
        pending_bookings, name='pendingbookings'),
    url(r'^showbooktimes/(\d+)$',
        show_booktimes, name='showbooktimes'),
]

sas/sas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from rest_framework import routers
from booking import serializerviews as views
from .views import index, faq

router = routers.DefaultRouter()
router.register(r'places', views.PlaceViewSet)
router.register(r'buildings', views.BuildingViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name="index"),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^booking/', include('booking.urls', namespace="booking")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')), 
    url(r'buildings/places/(?P<id_building>\d+)/$',views.BuildingPlaceList.as_view()),
    url(r'buildings/places/unoccupied/$',views.UnoccupiedPlaceList.as_view({'post': 'list'})),
    url(r'^faq/', faq, name="faq"),
]

sas/user/urls.py
from django.conf.urls import url
from .views import logout_user
from .views import delete_user
from .views import search_user
from .views import make_user_an_admin
from .views import LoginView, ChangePasswordView
from .views import settings
from .views import NewUserView, EditUserView

urlpatterns = [
    url(r'newuser/', NewUserView.as_view(), name='newuser'),
    url(r'login/', LoginView.as_view(), name='login'),
    url(r'logout/', logout_user, name='logout'),
    url(r'delete/$', delete_user, name='deleteuser'),
    url(r'^edituser/$', EditUserView.as_view(), name='edituser'),
    url(r'^change/$', ChangePasswordView.as_view(), name='changepassword'),
    url(r'^searchuser/$', search_user, name='searchuser'),
    url(r'^settings/$', settings, name='settings'),
    url(r'^usertoadmin/(\d+)$', make_user_an_admin, name='usertoadmin'),
]

sas/sas/views.py
from django.shortcuts import render
from user.forms import LoginForm


def index(request, login_form=LoginForm()):
    if hasattr(request, 'user') and request.user.is_authenticated():
        return render(request, 'sas/home.html', {})
    else:
        return render(request, 'sas/index.html', {'form': login_form})


def faq(request):
    return render(request, 'sas/faq.html')

sas/sas/templates/sas/base.html
{% load staticfiles bootstrap3 user_extras %}
{% load static %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SAS - FGA UnB | {% block title %}{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static "jquery/ui/jquery-ui.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style/base.css' %}" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "font-awesome/font-awesome.min.css" %}">
  {% block extrastyle %}{% endblock %}
</head>
<body>
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">
    <div class="container" style="position:absolute;right:0;">
      <div class="col-md-4 col-md-offset-8" style="float:right; padding-top:5px;">
        <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <div class="input-group input-group-sm"  style="max-width:250px;">
            <select class="form-control" style="padding:5px" name="language">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected="selected" {% endif %}>
                  {{ language.name_local }} ({{ language.code }})
                </option>
              {% endfor %}
            </select>
            <span class="input-group-btn">
              <button style="margin-left:1px" class="btn btn-success" type="submit">OK</button>
            </span>
          </div>
        </form>
      </div>
    </div>
  {% include "sas/menu.html" %}
  </header>

  <!-- page content -->
  <div class="content-wrapper">
    {% bootstrap_css %}
    <!-- Message modal-->
    {% if messages %}
      <!-- Modal message-->
      <div class="message-modal">
        <div id="message-modal" class="modal">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{% trans "Message" %}</h4>
              </div>
              <div class="modal-body">
                {% for message in messages %}
                  <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}<b>{% trans "Important" %}:</b> {% endif %}
                      {{ message }}
                  </p>
                {% endfor %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">{% trans "Close" %}</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
      </div>
      <!-- /.message-modal -->
    {% endif %}

    <!-- Main content -->
    <div class="content container">
    {% bootstrap_messages %}

      {% block content %}
      {{ content }}
      {% endblock %}

    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Footer -->
  <footer class="text-center">
      <div class="footer-above">
          <div class="container">
              <div class="row">
                  <div class="footer-col col-sm-6 col-xs-6">
                      <img src="{% static 'images/fga_logo.png' %}" class="fga-logo" alt="FGA logo">
                      <p><strong>Universidade de Brasília - Faculdade Gama</strong> <br>
                          Área Especial de Indústria Projeção A Brasília</p>
                  </div>
                  <div class="footer-col col-sm-6 col-xs-6">
                    <h3>{% trans "Contact" %}</h3>
                    <ul>
                      <li>{% trans "Telephone" %}: (61) 3107-8901</li>
                      <li>Email ({% trans "secretary" %}): <a href="mailto:unbgama@unb.br">unbgama@unb.br</a></li>
                      <li>Email ({% trans "board" %}): <a href="mailto:direcaofga@unb.br">direcaofga@unb.br</a></li>
                    </ul>
                  </div>
              </div>
          </div>
      </div>
  </footer>
</div>
<!-- end wrapper -->

<!-- REQUIRED JS SCRIPTS -->
<script src="{% static "jquery/jquery.min.js" %}"></script>
<script src="{% static "jquery/ui/jquery-ui.min.js" %}"></script>
<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>

{% block extrajs %}{% endblock %}
 
</body>
</html>

sas/sas/templates/sas/faq.html
{% extends 'sas/base.html' %}

{% load i18n %}
{% load bootstrap3 %}
{% bootstrap_messages %}

{% block title %}FAQ{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-8 col-sm-6 col-md-6 col-md-offset-3 col-xs-offset-2 col-sm-offset-3">
        <h1 class="text-center">{% trans "Frequently Asked Questions" %}</h1>
        <hr class="star-light">
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="intro-text">
            <p class="faq-content question"><span class="question-number">1)</span>  O sistema pode ser utilizado
                para reservar espaços em qualquer campus da UnB ?
            </p>
            <p class="faq-content answer">Não. No momento, este sistema está voltado apenas para alocação de espaços
                do Campus UnB Gama - FGA.
            </p>

            <p class="faq-content question"><span class="question-number">2)</span> Porque não aparece em minhas
                reservas a reserva que acabei de fazer de um laboratório/auditório?
            </p>
            <p class="faq-content answer">A reserva de laboratório/auditório precisa da aprovação de um coordenador.
                Assim que sua reserva for aprovada, aparecerá em "Minhas Reservas".
            </p>

            <p class="faq-content question"><span class="question-number">3)</span> Posso fazer reserva para qualquer
                dia da semana?
            </p>
            <p class="faq-content answer">Sim, qualquer dia e horário.
            </p>

            <p class="faq-content question"><span class="question-number">4)</span> Como faço para reservar todas as segundas
                de um semestre?
            </p>
            <p class="faq-content answer">Durante a criação da reserva, os dias da semana selecionados serão aplicados em
                todo o período informado.
            </p>

            <p class="faq-content question"><span class="question-number">5)</span> Como faço pra alterar a data da
                minha reserva?
            </p>
            <p class="faq-content answer">Uma reserva depois de finalizada não pode ser alterada, sendo necessário
                excluí-la e depois refazê-la com a data desejada.
            </p>

            <p class="faq-content question"><span class="question-number">6)</span> Como faço pra reservar uma sala para uma
                atividade que tem horários diferentes durante a semana?
            </p>
            <p class="faq-content answer"> Durante o cadastro de uma reserva só é possível selecionar um horário,
                portanto é preciso fazer duas ou mais reservas com o mesmo nome.
            </p>

            <p class="faq-content question"><span class="question-number">7)</span> Como proceder caso queira fazer a reserva de um
                espaço específico, mas já exista reserva no horário que preciso ?
            </p>
            <p class="faq-content answer"> Nesse caso, um coordenador que seja administrador do sistema deve ser contactado. Apenas
                administradores podem excluir reservas de outros usuários.
            </p>

            <p class="faq-content question"><span class="question-number">8)</span> Como posso visualizar as reservas existentes ?
            </p>
            <p class="faq-content answer"> Basta clicar em "Pesquisar" na página inicial, nela existem quatro filtros diferentes
                para realizar buscas de reservas.
            </p>

            <p class="faq-content question"><span class="question-number">9)</span> Como é feita a busca de reservas para cada filtro ?
            </p>
            <p class="faq-content answer"> O primeiro filtro serve para pesquisar as reservas de um espaço específico em uma semana. O
                segundo para ver os horários de uma reserva específica em um período de tempo. O terceiro ver as reserva feitas em
                em cada espaço de um prédio específico em um determinado dia. E o quarto para ver todas as reservas de um determinado
                espaço em um período de tempo.
            </p>

            <p class="faq-content question"><span class="question-number">10)</span> Cadastrei um dado errado no meu cadastro. É possível
                alterar ?
            </p>
            <p class="faq-content answer"> Sim, basta clicar onde está escrito seu nome, no canto superior direito. Após isso, clicar em
                "Dados Pessoais" e alterar o campo que preecheu errado.
            </p>

        </div>
    </div>
</div>
{% endblock %}

sas/sas/templates/sas/home.html
{% extends 'sas/base.html' %}
{% load i18n %}

{% load bootstrap3 %}
{% bootstrap_messages %}

{% block content %}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="intro-text">
            <h2>{% trans "Welcome" %}, {{ user.profile_user.full_name }}</h2>
            <span class="name">{% trans "Rooms Allocation System" %}</span>
            <hr class="star-light">
            <span class="skills">{% trans "Booking rooms, auditoriums and laboratories for teachers, students <br> and all the academic body of the university" %}.</span>
        </div>
    </div>
</div>
{% endblock %}

sas/sas/templates/sas/index.html
{% extends 'sas/base.html' %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans "Homepage" %}{% endblock %}
{% block content %}
    <!--index content -->
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="intro-text">
                <h1 class="content-title">{% trans "Welcome" %}</h1>
                <span class="name">{% trans "Rooms Allocation System" %}</span>
                <hr class="star-light">
                <span class="skills">{% trans "Booking rooms, auditoriums and laboratories for teachers, students <br> and all the academic body of the university" %}.</span>
            </div>
        </div>
    </div>
    <!--end index content -->
    {% if not request.user.is_authenticated %}
    <!--Modal Sign in/up -->
    <div class="modal fade in" id="sign" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <p class="modal-title" id="myModalLabel">Login</p>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="modal-col col-xs-6">
                            <div class="well">
                                <form id="loginForm" method="POST" action="/user/login/">
                                    {% csrf_token %}
									{% bootstrap_form form %}
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember" id="remember">
                                            {% trans "Remember me" %}
                                        </label>
                                    </div>
									{% bootstrap_form_errors form %}
                                    {% buttons %}
                                        <button type="submit" id="btn-login" class="btn btn-success btn-block">
                                        {% trans "Sign In" %}</button>
                                    {% endbuttons %}
                                    <div class="forgot-password">
                                        <a href="#forgot-password" data-toggle="modal" onclick="hideSignModal()">
                                        {% trans "Forgot Password" %}</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="modal-col col-xs-6">
                            <p class="lead">{% trans "I'm not registered yet" %}</p>
                            <ul class="list-unstyled" style="line-height: 2">
                                <li>{% trans "Registered user can book" %}:</li> <br>
                                <li><span class="glyphicon glyphicon-ok text-success"></span>{% trans " Laboratories" %}</li>
                                <li><span class="glyphicon glyphicon-ok text-success"></span>{% trans " Auditoriums" %}</li>
                                <li><span class="glyphicon glyphicon-ok text-success"></span>{% trans " Rooms" %}</li>
                            </ul>
                            <p><a href="/user/newuser/" class="btn btn-info btn-block">{% trans "Sign Up" %}</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" role="dialog" id="forgot-password">
        <div class="modal-dialog">
            <div class="modal-content content-password">
               <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <p class="modal-title" id="myModalLabel">{% trans "Forgot Password" %}</p>
                </div>
                <div class="modal-body modal-password">
                    <div class="row">
                        <div class="modal-col col-password col-xs-12">
                            <p class="description">{% trans "Type your email and an automatic message will be sent to it containing a new password. This must be changed posteriorly." %}</p>
                            <div class="control-group">
                                <label class="control-label">Email:</label>
                                <input class="form-control" type="email" name="password" id="password">
                            </div>
                            <div class="modal-footer">
                                <a href="#" class="btn btn-success btn-email btn-block">{% trans "Recover Password" %}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--end modal sign in/up -->

{% block extrajs %}
<script type="text/javascript">
//Show modal sign in/up according to parameter
  $(window).load(function(){
    var url = window.location.href;
    if(url.indexOf('?showLoginModal=yes') != -1) {
      $('#sign').modal('show');
    }
  });
{% if form.errors %}
	$(window).load(function(){
		$('#sign').modal('show');
	});
{% endif %}
</script>
{% endblock %}

{% endif %}
{% endblock %}

sas/sas/templates/sas/menu.html
{% load i18n user_extras %}

<!-- Menu -->
<div class="navbar navbar-custom" role="navigation">
   <div class="container">
       <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
       </div>
       <div class="collapse navbar-collapse navbar-ex1-collapse">
         <ul class="nav navbar-nav">
             <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
             <li><a href="{% url 'booking:searchbookingtable' %}">{% trans "Search" %}</a></li>
             {% if not request.user|is_admin and request.user.is_authenticated %}
             <li><a href="{% url 'booking:newbooking2' %}">{% trans "Book a Place" %}</a></li>
             {% endif %}
             <!-- IF request.user is ADM -->
               {% if request.user|is_admin %}
               <ul class="nav navbar-nav pull-right">
                   <li class="dropdown">
                       <a href="#" class="dropdown-toggle" type="button" id="user-link"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                          {% trans "Bookings" %}
                           <span class="caret"></span>
                       </a>
                       <ul class="dropdown-menu pull-right" aria-labelledby="user-link">
                         <li class="user-menu-info"><a href="{% url 'booking:newbooking' %}">
                           <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                            {% trans "Book a Place" %}</a></li>
                           <li class="user-menu-info"><a href="{% url 'booking:allbookings' %}">
                             <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                            {% trans "View All Bookings" %}</a></li>
                           <li class="user-menu-info"><a href="{% url 'booking:pendingbookings' %}">
                             <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                            {% trans "Requests" %}</a></li>
                           <li role="separator" class="divider"></li>
                       </ul>
                   </li>
               </ul>
               <li><a href="{% url 'user:searchuser' %}">{% trans "Users" %}</a></li>
               {% endif %}
             <li><a href="{% url 'faq' %}">FAQ</a></li>
         </ul>
         {% if request.user.is_authenticated %}
         <ul class="nav navbar-nav pull-right">
             <li class="dropdown">
                 <a href="#" class="dropdown-toggle" type="button" id="user-link"
                     data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                     {% trans "Hi" %}, {{ user.profile_user.full_name }}
                     <span class="caret"></span>
                 </a>
                 <ul class="dropdown-menu pull-right" aria-labelledby="user-link">
                     <li class="user-menu-info"><a href="{% url 'user:edituser' %}">
                       <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                      {% trans "Personal Data" %}</a></li>
                     <li class="user-menu-info"><a href="{% url 'booking:searchbooking' %}">
                       <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                      {% trans "My Bookings" %}</a></li>
                     <li role="separator" class="divider"></li>
                     {% if request.user|is_admin %}
                     <li class="user-menu-info"><a href="{% url 'user:settings' %}">
                       <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                       {% trans "Settings" %}</a></li>
                     {% endif %}
                     <li class="user-menu-info"><a href="{% url 'user:logout' %}">
                       <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                       {% trans "Logout" %}</a></li>
                 </ul>
             </li>
         </ul>
         {% else %}
         <ul class="nav navbar-nav pull-right">
             <li>
              <a id="enter-button" class="btn btn-success" data-toggle="modal" href="{% url 'index' %}?showLoginModal=yes">
                {% trans "Sign In | Sign Up" %}
              </a>
             </li>
         </ul>
         {% endif %}
     </div>
   </div>
</div>
<!--end menu -->