sas/booking/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import new_booking
from .views import NewBooking
from .views import search_booking
from .views import SearchBookingQueryView
from .views import search_booking_table
from .views import confirm_booking
from .views import cancel_booking
from .views import delete_booking
from .views import delete_booktime
from .views import all_bookings
from .views import pending_bookings
from .views import approve_booking
from .views import deny_booking
from .views import show_booktimes
from .views import booking_details
from .views import tagged_bookings

urlpatterns = [
    url(r'^newbooking/$',
        new_booking, name='newbooking'),
    url(r'^newbooking2/$',
        NewBooking.as_view(), name='newbooking2'),
    url(r'^searchbooking/$',
        search_booking, name='searchbooking'),
    url(r'^confirmbooking/(\d+)$',
        confirm_booking, name='confirmbooking'),
    url(r'^cancelbooking/(\d+)$',
        cancel_booking, name='cancelbooking'),
    url(r'^searchbookingquery/$',
        SearchBookingQueryView.as_view(),
        name='searchbookingquery'),
    url(r'^searchbookingg/$',
        SearchBookingQueryView.as_view(), name='searchbookingtable'),
    url(r'^deletebooking/(\d+)$',
        delete_booking, name='deletebooking'),
    url(r'^approvebooking/(\d+)$',
        approve_booking, name='approvebooking'),
    url(r'^denybooking/(\d+)$',
        deny_booking, name='denybooking'),
    url(r'^taggedbookings/(\d+)$',
        tagged_bookings, name='taggedbookings'),
    url(r'^bookingdetails/(\d+)$',
        booking_details, name='bookingdetails'),
    url(r'^deletebooktime/(\d+)/(\d+)$',
        delete_booktime, name='deletebooktime'),
    url(r'^allbookings/$',
        all_bookings, name='allbookings'),
    url(r'^pendingbookings/$',
        pending_bookings, name='pendingbookings'),
    url(r'^showbooktimes/(\d+)$',
        show_booktimes, name='showbooktimes'),
]

sas/sas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from rest_framework import routers
from booking import serializerviews as views
from .views import index, faq

router = routers.DefaultRouter()
router.register(r'places', views.PlaceViewSet)
router.register(r'buildings', views.BuildingViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name="index"),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^booking/', include('booking.urls', namespace="booking")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')), 
    url(r'buildings/places/(?P<id_building>\d+)/$',views.BuildingPlaceList.as_view()),
    url(r'buildings/places/unoccupied/$',views.UnoccupiedPlaceList.as_view({'post': 'list'})),
    url(r'^faq/', faq, name="faq"),
]

sas/booking/models.py
from django.utils.translation import ugettext_lazy as _, ugettext as __
from django.db import models, connection
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError
from datetime import datetime, timedelta
import copy
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied

CATEGORY = (('', '----------'), ('1', _('Student')),
            ('2', _('Teaching Staff')), ('3', _('Employees')))

WEEKDAYS = (('0', _("Monday")), ('1', _("Tuesday")), ('2', _("Wednesday")),
            ('3', _("Thursday")), ('4', _("Friday")), ('5', _("Saturday")),
            ('6', _("Sunday")))

ENGINEERINGS = (('0', '----'), ('1', _('Software')), ('2', _('Eletronic')),
               ('3', _('Energy')), ('4', _('Automotive')),
               ('5', _('Aerospace')), ('6', _('Engineerings')))


class Building(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Place(models.Model):
    name = models.CharField(max_length=200)
    capacity = models.PositiveSmallIntegerField()
    building = models.ForeignKey(Building, related_name='building')
    location = models.CharField(max_length=50)
    place_id = models.CharField(max_length=200)
    is_laboratory = models.BooleanField(default=False)

    def __str__(self):
        try:
            return (self.building.name + " | " + self.name +
                    " - Cap. " + str(self.capacity))
        except:
            return self.name


class BookTime(models.Model):
    start_hour = models.TimeField(null=False, blank=False)
    end_hour = models.TimeField(null=False, blank=False)
    date_booking = models.DateField(null=False, blank=False)

    def add_days(self, nr_days):
        delta = timedelta(days=nr_days)
        self.date_booking = self.date_booking + delta

    def next_week_day(self, nr_weekday):
        diff_of_weekdays = self.date_booking.weekday() - nr_weekday
        if diff_of_weekdays > 0:
            self.add_days(7 - diff_of_weekdays)
        elif diff_of_weekdays < 0:
            self.add_days(diff_of_weekdays * (-1))
        else:
            self.add_days(7)

    def get_str_weekday(self):
        return self.date_booking.strftime("%A")

    def __str__(self):
        return (str(self.date_booking) + " | " +
                str(self.start_hour) + " - " + str(self.end_hour))

    def delete_booktime(self, booking):
        if booking.time.count() == 1:
            booking.delete()
        else:
            booking.time.remove(self)
            super(BookTime, self).delete()


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    @staticmethod
    def get_tags():
        tags = Tag.objects.all()
        choices = []
        for tag in tags:
            new_choice = (tag, tag)
            choices.append(new_choice)
        choices = sorted(choices, key=lambda tag_tuple:
                         tag_tuple[0].name)
        choices.insert(0, ('', ''))
        return choices


BOOKING_STATUS = ((0, _("Denied")), (1, _("Pending")), (2, _("Approved")))


class Booking(models.Model):
    user = models.ForeignKey(User, related_name="bookings",
                             on_delete=models.CASCADE)
    responsible = models.CharField(max_length=100, default=' ')
    time = models.ManyToManyField(BookTime, related_name="booking_time")
    place = models.ForeignKey(Place, related_name="booking_place")
    name = models.CharField(max_length=50)
    start_date = models.DateField(null=False, blank=False)
    end_date = models.DateField(null=False, blank=False)
    status = models.PositiveSmallIntegerField(choices=BOOKING_STATUS,
                                              default=2)
    tags = models.ManyToManyField(Tag, related_name="tags")

    engineering = models.CharField(choices=ENGINEERINGS, max_length=5)

    def __str__(self):
        return (self.name + " " + self.user.email + " | " + str(self.place) +
                " - " + str(self.start_date) + " - " + str(self.end_date))

    def exists(self, start_hour, end_hour, week_days):
        week_days = [1 if int(x) == 6 else int(x) + 2 for x in week_days]
        return Booking.objects.filter(place_id = self.place_id,
                                   time__date_booking__gte = self.start_date,
                                   time__date_booking__lt = self.end_date,
                                   time__start_hour = start_hour,
                                   time__end_hour = end_hour,
                                   time__date_booking__week_day__in = week_days
                                   ).exists()


    def save(self, *args, **kwargs):
        if (self.place.is_laboratory and not
                self.user.profile_user.is_admin()):
            self.status = 1  # status for pending booking
        if Place.objects.filter(name=self.place.name):
            self.place = Place.objects.get(name=self.place.name)
        else:
            self.place.save()
            self.place_id = self.place.pk
        super(Booking, self).save(*args, **kwargs)

    def delete(self):
        self.time.all().delete()
        super(Booking, self).delete()

    def update_status(self, status):
        Booking.objects.filter(pk=self.pk).update(status=status)
        self.refresh_from_db()

    def update_start_date(self):
        all_booktimes = self.time.order_by('date_booking')
        self.start_date = all_booktimes.first().date_booking
        self.save()

    def update_end_date(self):
        all_booktimes = self.time.order_by('date_booking')
        self.end_date = all_booktimes.last().date_booking
        self.save()

    def delete_booktime(self, id_booktime, user):
        booktime = BookTime.objects.get(pk=id_booktime)
        all_booktimes = self.time.order_by('date_booking')
        if (user.profile_user.is_admin() or self.user.id == user.id) and \
                booktime in all_booktimes:
            booktime.delete()
            if(all_booktimes.count() > 1):
                self.update_start_date()
                self.update_end_date()
        else:
            raise PermissionDenied()

    @staticmethod
    def get_bookings():
        bookings = Booking.objects.values('name').order_by('-name').distinct()
        choices = ()
        for booking in bookings:
            new_choice = (booking['name'], booking['name'])
            choices = (new_choice,) + choices
        return choices

    @staticmethod
    def get_responsibles():
        bookings = Booking.objects.values('responsible').distinct()
        choices = ()
        for booking in bookings:
            new_choice = (booking['responsible'], booking['responsible'])
            choices = (new_choice,) + choices
        return choices

    @staticmethod
    def get_places(bookings):
        place_name = []
        place = []

        for booking in bookings:
            p = booking.place.name.split('-')
            if (booking.status > 1) and (p[1] not in place_name):
                place_name.append(p[1])
                place.append(booking.place)
        return place, place_name


class Validation():

    def hasNumbers(self, string):
        if any(char.isdigit() for char in string):
            return True

    def hasLetters(self, number):
        if any(char.isalpha() for char in number):
            return True

    def hasSpecialCharacters(self, string):
        for character in '@#$%^&+=/\{[]()}-_+=*!§|':
            if character in string:
                return True


def date_range(start_date, end_date):
    return [start_date + timedelta(days=x)
            for x in range(0, (end_date - start_date).days + 1)]

sas/booking/templates/booking/newBooking2.html
{% extends 'sas/base.html' %}

{% load i18n %}
{% load bootstrap3 staticfiles %}
{% bootstrap_messages %}

{% block title %} {% trans "New Booking" %} {% endblock %}


{% block content %}
    <div class="row">
        <form id="newbooking" action="{% url 'booking:newbooking' %}" method="POST">
        {% csrf_token %}
        <input class="" id="id_date_options_1" name="date_options" title="" type="hidden" value="opt_select_date" >
	    <div id="con" class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
            <h1 class="text-center">{% trans "New Booking" %}</h1>
            <hr class="star-light"></hr>
            <div id="breadcrumbs">
                <ul class="bread-crumbs">
                    <li>
                        <i class="glyphicon glyphicon-pencil"></i>
                        {% trans "Title" %}
                    </li>
                    <li>
                        <i class="glyphicon glyphicon-calendar"></i>
                        {% trans "Date" %}
                    </li>
                    <li>
                        <i class="glyphicon glyphicon-home"></i>
                        {% trans "Building" %}
                    </li>
                    <li>
                        <i class="glyphicon glyphicon-tent"></i>
                        {% trans "Espace" %}
                    </li>
              <!-- Job complete -->
                    <li>
                        <i class="glyphicon glyphicon-ok-sign"></i>
                        {% trans "Finish" %}
                    </li>
                </ul>
            </div>
            <div id="page1" class="form-content">
                <div class="form-group">
                    <label class="control-label" id="id_name">{% trans "Booking name" %}:</label>
                    <input id="name_of_booking" name="name" class="form-control" type="text" \>
                </div>
                <button id="next-date" type="button" class="btn btn-primary btn-newbooking" value="Next">
                  {% trans "Next" %}
                  <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </button>
            </div>
            <div id="page2" class="form-content container">
              <div class="row">
                <div class="col-sm-3">
                  <label>
                    <input type="radio" name="times" value="oneday" checked /> {% trans "Just one day" %}
                  </label>
                </div>
                <div class="col-sm-3">
                  <label>
                    <input type="radio" name="times" value="interval" /> {% trans "Interval" %}
                  </label>
                </div>
              </div>
                <hr>
                <div id="one-day">
                    <div class="form-group newbooking-dates">
                        <label class="control-label" for="id_one_day_date">{% trans "Date" %}:</label>
                        <input class="form-control newbooking-dates-input datepicker1" id="id_one_day_date"
                            placeholder="{% trans 'dd/mm/yyyy' %}" name="date" type="text" style="width:200px">
                    </div>
                </div>
                <div id="period-dates" class="row">
                    <div class="form-group col-xs-12 col-sm-6 newbooking-dates">
                        <label class="control-label" for="id_start_date">{% trans "Start Date" %}:</label>
                        <input class="form-control newbooking-dates-input datepicker1" id="id_start_date"
                            placeholder="{% trans 'dd/mm/yyyy' %}" name="start_date" type="text" style="width:200px">
                    </div>
                    <div class="form-group col-xs-12 col-sm-6 newbooking-dates">
                        <label class="control-label" for="id_end_date">{% trans "End Date" %}:</label>
                        <input class="form-control newbooking-dates-input datepicker1" id="id_end_date"
                            placeholder="{% trans 'dd/mm/yyyy' %}" name="end_date" type="text" style="width:200px">
                    </div>
                </div>
                <div id="times" class="row" style="padding:20px 0">
                  <div class="col-sm-6">
                    <div class"booking-slider col-xs-12 col-md-6">
                        <div style="max-width:200px;">
                          <label>{% trans "Begin Time" %}</label>
                          <div id="slider_begin_time" ></div>
                        </div>
                        <div style="padding:10px 0">
                          <input id="input_slider_begin_time" name="start_hour" class="form-control" style="width:200px" type="text" />
                        </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class"booking-slider col-xs-12 col-md-6">
                        <div style="max-width:200px;">
                          <label>{% trans "End Time" %}</label>
                          <div id="slider_end_time" ></div>
                        </div>
                        <div style="padding:10px 0">
                            <input id="input_slider_end_time" name="end_hour"  class="form-control" style="width:200px" type="text" />
                        </div>
                    </div>
                </div>
              </div>

                <div id="id_week_days" class="row">
                    <div class="col-xs-6 col-md-3">
                        <div class="checkbox newbooking-checkbox">
                            <label for="id_week_days_0">
                                <input class="" id="id_week_days_0" name="week_days" title=""
                                    type="checkbox" value="0"> {% trans "Monday" %}
                            </label>
                        </div><br>
                        <div class="checkbox newbooking-checkbox">
                            <label for="id_week_days_1">
                                <input class="" id="id_week_days_1" name="week_days" title=""
                                    type="checkbox" value="1"> {% trans "Tuesday" %}
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <div class="checkbox newbooking-checkbox">
                            <label for="id_week_days_2">
                                <input class="" id="id_week_days_2" name="week_days" title=""
                                    type="checkbox" value="2"> {% trans "Wednesday" %}
                            </label>
                        </div><br>
                        <div class="checkbox newbooking-checkbox">
                            <label for="id_week_days_3">
                                <input class="" id="id_week_days_3" name="week_days" title=""
                                    type="checkbox" value="3"> {% trans "Thursday" %}
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <div class="checkbox newbooking-checkbox">
                            <label for="id_week_days_4">
                                <input class="" id="id_week_days_4" name="week_days" title=""
                                    type="checkbox" value="4"> {% trans "Friday" %}
                            </label>
                        </div><br>
                        <div class="checkbox newbooking-checkbox">
                            <label for="id_week_days_5">
                            <input class="" id="id_week_days_5" name="week_days" title=""
                                type="checkbox" value="5"> {% trans "Saturday" %}
                            </label>
                        </div>
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <div class="checkbox newbooking-checkbox">
                            <label for="id_week_days_6">
                                <input class="" id="id_week_days_6" name="week_days" title=""
                                    type="checkbox" value="6"> {% trans "Sunday" %}
                            </label>
                        </div>
                    </div>
                </div>
                <button type="button" class="btn btn-primary btn-newbooking btn-back" value="2">
                  <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                  {% trans "Back" %}
                </button>
                <button type="button" id="next-building" class="btn btn-primary btn-newbooking" value="Next">
                  {% trans "Next" %}
                  <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </button>
            </div>
            <div id="page3" class="form-content">
                <input id="booking-building-hidden" type="hidden" name="building" />
                <table id="booking-buildings" class="place" style="table-layout:fixed;">
                    <tr>
                    </tr>
                </table>
                <button type="button" class="btn btn-primary btn-newbooking btn-back" value="3">
                  <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                  {% trans "Back" %}
                </button>
                <button type="button" id="next-place" class="btn btn-primary btn-newbooking" value="Next">
                  {% trans "Next" %}
                  <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </button>
            </div>
             <div id="page4" class="form-content">
                <input id="booking-place-hidden" type="hidden" name="place" />
                <table id="booking-places" class="place">
                    <tr>
                    </tr>
                </table>
                <button type="button" class="btn btn-primary btn-newbooking btn-back" value="4">
                  <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                  {% trans "Back" %}
                </button>
                <button id="next-finish" type="submit" class="btn btn-primary btn-newbooking" value="Next">
                  {% trans "Next" %}
                  <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </button>
            </div>
		</div>
        </form>
	</div>
{% endblock %}


{% block extrastyle %}
<link rel="stylesheet" href="{% static 'jquery/ui/jquery-ui.min.css' %}" />
<link rel="stylesheet" href="{% static 'booking/css/newbooking.css' %}" />
{% endblock %}

{% block extrajs %}
<script src= "{% static 'jquery/ui/jquery-ui.min.js' %}"></script>
<script src= "{% static 'jquery/ui/datepicker-pt-BR.js' %}"></script>
<script src="{% static "booking/js/place.js" %}"></script> 
<script src="{% static "booking/js/building.js" %}"></script> 
<script src="{% static "booking/js/booking.js" %}"></script> 
<script src="{% static "booking/js/newbooking.js" %}"></script>
<script type="text/javascript">
 $(document).ready(function () {
	    $('.datepicker1').datepicker({
			inline: true,
			useCurrent: true,
			autoclose: true,
	});
    {% if LANGUAGE_CODE == "en" %}
            $('.datepicker1').datepicker( "option", $.datepicker.regional[ "" ] );
    {% else %}
            $('.datepicker1').datepicker( "option", $.datepicker.regional[ "{{ LANGUAGE_CODE|default:"" }}" ] );
    {% endif %}

    $('html').bind('keypress', function(e){
        if(e.keyCode == 13){
            return false;
        }   
    });

});   
</script>

{% endblock %}

sas/booking/templates/booking/searchBookingTable.html
{% extends 'sas/base.html' %}

{% load i18n %}
{% load bootstrap3 %}
{% bootstrap_messages %}

{% block title %} {% trans "New Booking" %} {% endblock %}


{% block content %}
	<div class="row">
		<div class="col-xs-8 col-sm-6 col-md-6 col-md-offset-3 col-xs-offset-2 col-sm-offset-3">
			<h1 class="text-center">{% trans "Rooms Booking" %}</h1>
			<hr class="star-light">
			<div class="form-content" >
			   <form class="form-horizontal" method = 'POST'>
					{% csrf_token %}
					{% bootstrap_form form_booking %}
					{% buttons %}
						<button class="btn btn-info btn-block" type = 'submit'>{% trans "Perform Search" %}</button>
					{% endbuttons %}
				</form>
			</div>
		</div>
	</div>

{% endblock %}

sas/booking/templates/booking/template_table.html
{% extends 'sas/base.html' %}

{% load i18n %}
{% load bootstrap3 staticfiles %}
{% load check_table %}
{% load user_extras %}
{% bootstrap_messages %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'style/bookingtable.css' %}">
<link rel="stylesheet" href="{% static 'plugins/selectize/css/selectize.bootstrap3.min.css' %}" />
{% endblock %}

{% block title %} {% trans "Template Bookings Reports" %} {% endblock %}


{% block content %}
<h1 style="text-align:center;text-transform:capitalize">{{ name }}</h1>
<h2 style="text-align:center;text-transform:capitalize"><small>{{ table_header }}</small></h2>

<hr class="star-light">
<br>
<div class='col-xs-12' style="overflow-x:scroll">
 <table border='0' cellpadding='0' cellspacing='0' width='100%'>
  <thead>
    <tr class='days'><th></th><th colspan="{{  n  }}" class="text-center">{{ table_header }}</th></tr>
    <tr class='days'>
    <th class='days'>{% trans "Time" %}</th>
      {% for column in column_header %}
        <th class='days'><big>{{ column }}</big></th>
      {% endfor %}
    </tr>
  </thead>

  <tbody>
    {% for id,hour in hours %}
      <tr>
         <td class='time'> <strong>{{hour}}</strong></td>
           {% for cell_table in table %}
            {% with forloop.counter0 as count %}
              {% if not cell_table%}
      				<td class="cs335 small text-center" style="color:black">
                {% if request.user.is_authenticated %}
                  <button class="btn btn-xs btn-primary" data-href="{% url 'booking:newbooking' %}"
                      data-toggle="modal" data-start-hour="{{id|search_hour:0}}" data-end-hour="{{id|search_hour:1}}" data-start-date="{{ days|aux_search_date:n|search_date:count }}" data-end-date="{{ days|aux_search_date:n|search_date:count }}"
                      data-place-pk="{{place|search_place:count}}" data-building-pk="{{ place|search_building:count }}" data-target="#modalNewBooking" id="create-booking"
                      data-date-options="opt_select_date">
                      <span class="glyphicon glyphicon-plus-sign" ></span> {% trans "Book" %}
                  </button>
                {%endif%}
              </td>
              {% else%}
                <td class="cs335 small text-center" {% if cell_table|check_tooltip:id %}
                    data-tooltip="{{ cell_table|check_tooltip:id }}"{% endif %}
                    style="color:black">

                  {% if cell_table|check_table:id %}
                     {{ cell_table|check_table:id }}
                  {% elif request.user.is_authenticated %}
                  <button class="btn btn-xs btn-primary" data-href="{% url 'booking:newbooking' %}"
                      data-toggle="modal" data-start-hour="{{id|search_hour:0}}" data-end-hour="{{id|search_hour:1}}" data-start-date="{{ days|aux_search_date:n|search_date:count }}" data-end-date="{{ days|aux_search_date:n|search_date:count }}"
                      data-place-pk="{{ place|search_place:count }}" data-place="{{cell_table.0.1.place}}" data-building-pk="{{ place|search_building:count }}" data-target="#modalNewBooking" id="create-booking" data-date-options="opt_select_date">
                      <span class="glyphicon glyphicon-plus-sign" ></span> {% trans "Book" %}
                  </button>
                  {%endif%}

                </td>
              {% endif %}
            {% endwith %}
           {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>
<br>
<!-- Modal -->
<div class="modal fade" id="modalNewBooking" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="dialog">
    <div class="modal-content">
      <div class="modal-header delete-header">
        <button class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p class="modal-title" id="myModalLabel">{% trans "Confirm booking creation" %}</p>
      </div>
      <form class="form-horizontal" method = 'POST' action="{% url 'booking:newbooking' %}">
       {% csrf_token %}
        <div class="modal-body">
          <p>{% trans "Are you sure you want to book this place?" %}<br>
            <strong><span id="place"></span></strong>
          </p>
          <input type="hidden" class="form-control" id="id_date_options_1" name="date_options" title="" required>
          <input type="hidden" class="form-control" id="id_building" name="building" title="" required>
          <input type="hidden" class="form-control" id="id_place" name="place" title="" required>
          <input type="hidden" class="form-control" id="id_start_hour" name="start_hour" title="" required>
          <input type="hidden" class="form-control" id="id_end_hour" name="end_hour" title="" required>
          <input type="hidden" class="form-control" id="id_start_date" name="start_date" title="" required>
          <input type="hidden" class="form-control" id="id_end_date" name="end_date" title="" required>

          <label class="control-label" for="id_name">Booking Name:</label>
          <input class="form-control" id="id_name" name="name" placeholder="" title="" type="text" required />

          <label class="control-label" for="id_responsible">Tags:</label>

          <select class="form-control selectize_multiple" id="id_tags" name="tags" placeholder="" title="">
            {% search_tags as tags %}
            {% for counter, tag in tags %}
            <option value={{counter}}> {{counter}} </option>

            {% endfor %}
          </select>
          {% if user|is_admin %}
            <label class="control-label" for="id_responsible">Responsible:</label>

            <select class="form-control selectize" id="id_responsible" name="responsible" placeholder="" title="">
              {% search_user as users %}
              {% for counter, user in users %}
              <option> {{counter}} </option>

              {% endfor %}
            </select>
          {% endif %}

        </div>
        <div class="modal-footer">
           <button class="btn btn-primary btn-ok" type="submit" id="action-create">
            {% trans "Book" %}
            </button>
          <a class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</a>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}



{% block extrajs %}
<script src="{% static 'plugins/selectize/js/selectize.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/responsive.bootstrap.min.js' %}"></script>
<!-- page script -->
<script>

// $(document).ready(function () {

//   $("#id_responsible").selectize({
//       delimiter: ',',
//       persist: false,
//       maxItems:1,
//       create: function(input) {
//           return {
//               value: input,
//               text: input
//           }
//       }
//   });
// });
$("#id_tags").selectize({
    delimiter: ',',
    persist: false,
    maxItems:10,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
});

$('#modalNewBooking').on('show.bs.modal', function(e) {
    $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
});

$(document).on("click", "#create-booking", function () {
     var place_pk = $(this).data('place-pk');
     var building_pk = $(this).data('building-pk');
     var start_hour = $(this).data('start-hour');
     var end_hour = $(this).data('end-hour');
     var start_date = $(this).data('start-date');
     var end_date = $(this).data('end-date');
     var select_date = $(this).data('date-options');

     $(".modal-body #id_place").val( place_pk );
     $(".modal-body #id_building").val( building_pk );
     $(".modal-body #id_start_hour").val( start_hour );
     $(".modal-body #id_end_hour").val( end_hour );
     $(".modal-body #id_start_date").val( start_date );
     $(".modal-body #id_end_date").val( end_date );
     $(".modal-body #id_date_options_1").val( select_date );

});
</script>
{% endblock %}