sas/sas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from rest_framework import routers
from booking import serializerviews as views
from .views import index, faq

router = routers.DefaultRouter()
router.register(r'places', views.PlaceViewSet)
router.register(r'buildings', views.BuildingViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name="index"),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^booking/', include('booking.urls', namespace="booking")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')), 
    url(r'buildings/places/(?P<id_building>\d+)/$',views.BuildingPlaceList.as_view()),
    url(r'buildings/places/unoccupied/$',views.UnoccupiedPlaceList.as_view({'post': 'list'})),
    url(r'^faq/', faq, name="faq"),
]

sas/user/urls.py
from django.conf.urls import url
from .views import logout_user
from .views import delete_user
from .views import search_user
from .views import make_user_an_admin
from .views import LoginView, ChangePasswordView
from .views import settings
from .views import NewUserView, EditUserView

urlpatterns = [
    url(r'newuser/', NewUserView.as_view(), name='newuser'),
    url(r'login/', LoginView.as_view(), name='login'),
    url(r'logout/', logout_user, name='logout'),
    url(r'delete/$', delete_user, name='deleteuser'),
    url(r'^edituser/$', EditUserView.as_view(), name='edituser'),
    url(r'^change/$', ChangePasswordView.as_view(), name='changepassword'),
    url(r'^searchuser/$', search_user, name='searchuser'),
    url(r'^settings/$', settings, name='settings'),
    url(r'^usertoadmin/(\d+)$', make_user_an_admin, name='usertoadmin'),
]

sas/user/forms.py
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from .models import UserProfile, Validation
from .models import CATEGORY, ENGINEERING, Settings
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError

class UserProfileForm(forms.Form):
    name = forms.CharField(
        label=_('Name:'),
        widget=forms.TextInput(attrs={'placeholder': ''}))
    registration_number = forms.CharField(
        label=_('Registration number:'),
        widget=forms.TextInput(attrs={'placeholder': ''}))
    category = forms.ChoiceField(choices=CATEGORY, label=_('Category:'))
    email = forms.EmailField(
        label=_('Email:'),
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'example@email.com'}),
        error_messages={'invalid': _('Email address must \
                                       be in a valid format.')})
    password = forms.CharField(
        label=_('Password:'),
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': ''}))



class LoginForm(UserProfileForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self ).__init__(*args, **kwargs)
        self.fields.pop("category")
        self.fields.pop("name")
        self.fields.pop("registration_number")

    def authenticate_user(self):
        username = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is None:
            raise ValidationError({'password':
                                  [_('Email or Password does not match'), ]})
        return user

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        self.authenticate_user()
        return cleaned_data


class PasswordForm(UserProfileForm):

    new_password = forms.CharField(
        label=_('New Password:'),
        widget=forms.PasswordInput(attrs={'placeholder': ''}))
    renew_password = forms.CharField(
        label=_('Repeat Password:'),
        widget=forms.PasswordInput(attrs={'placeholder': ''}))

    def __init__(self, *args, **kwargs):
        super(PasswordForm, self ).__init__(*args, **kwargs)
        self.fields.pop("email")
        self.fields.pop("category")
        self.fields.pop("name")
        self.fields.pop("registration_number")

    def save(self, user):
        password = self.cleaned_data.get("new_password")
        user.set_password(password)
        user.save()

    def is_password_valid(self, username):
        cleaned_data = super(PasswordForm, self).clean()
        password = cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is None:
            self.add_error('password', _('Current password is wrong'))
            return False
        return True

    def clean(self):
        cleaned_data = super(PasswordForm, self).clean()
        password1 = cleaned_data.get('new_password')
        password2 = cleaned_data.get('renew_password')
        if password1 and password2 and password1 != password2:
            raise ValidationError({'renew_password': [_('Passwords \
                                                         do not match'), ]})

        if len(password1) < 6 or len(password1) > 15:
            raise ValidationError({'new_password': [_('Password must be \
                                                       between 6 and 15 \
                                                       characters.'), ]})

class UserForm(UserProfileForm):

    repeat_password = forms.CharField(
        label=_('Repeat Password:'),
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': ''}))

    engineering = forms.ChoiceField(choices=ENGINEERING,
                                    label=_('Engineering:'))
    def __init__(self, *args, **kwargs):
        instance = kwargs.pop("instance", None)
        editing = kwargs.pop("editing", None)
        super(UserForm, self ).__init__(*args, **kwargs)
        if instance is not None:
            self.__dict__["instance"] = instance
        if instance is not  None or editing is not None:
            self.fields.pop("password")
            self.fields.pop("repeat_password")
        if editing is None and instance is not None:
            self.fields["email"].initial = instance.user.email
            self.fields["category"].initial = instance.category
            self.fields["name"].initial = instance.full_name()
            self.fields["registration_number"].initial = instance.registration_number
            self.fields['engineering'].initial = instance.engineering

    def set_fields(self, userprofile):
        userprofile.name(self.cleaned_data.get('name'))
        userprofile.user.email = self.cleaned_data.get('email')
        userprofile.user.username = userprofile.user.email
        userprofile.engineering = self.cleaned_data.get('engineering')
        userprofile.registration_number = self.cleaned_data.get('registration_number')
        userprofile.category = self.cleaned_data.get('category')

    def update(self, userprofile):
        self.set_fields(userprofile)
        try:
            userprofile.save()
        except:
           raise Exception(_("Something went wrong so we could not save \
                             your data. Try again later"))
        return userprofile

    def insert(self):
        userprofile = UserProfile()
        userprofile.user = User()
        self.set_fields(userprofile)
        userprofile.user.set_password(self.cleaned_data.get('password'))
        try:
            userprofile.save()
            userprofile.make_as_academic_staff()
        except e:
           raise Exception(_("Something went wrong so we could not save \
                             your data. Try again later"))
        return userprofile

    def clean_registration_number(self):
        validation = Validation()
        rn = self.cleaned_data["registration_number"]
        if hasattr(self, "instance") and self.instance.registration_number == rn:
            return rn
        elif UserProfile.objects.filter(registration_number=rn).exists():
                raise ValidationError(_('Registration Number already exists.'))
        if (len(rn) is not 9):
            raise ValidationError([_('Registration Number must have 9 characters.'), ])
        if validation.hasSpecialCharacters(rn):
            raise ValidationError([_('Registration Number cannot \
                                      contain special characters.'), ])
        if validation.hasLetters(rn):
            raise ValidationError([_('Registration Number cannot \
                                      contain letters.'), ])

        return rn

    def clean_email(self):
        email = self.cleaned_data["email"]
        if hasattr(self,"instance") and self.instance.user.email == email:
            return email
        elif User.objects.filter(email=email).exists():
                raise ValidationError(_('Email already used.'))

        return email

    def clean_name(self):
        validation = Validation()
        name = self.cleaned_data['name']

        if (len(name) < 2 or len(name) > 50):
            raise ValidationError([_('Name must be between 2 and \
                                               50 characters.'), ])

        if validation.hasSpecialCharacters(name):
            raise ValidationError([_('Name cannot contain special \
                                               characters.'), ])

        if validation.hasNumbers(name):
            raise ValidationError([_('Name cannot contain numbers.'), ])
        return name

    def clean(self):
        cleaned_data = super(UserForm, self).clean()

        if "password" in self.fields and "repeat_password" in self.fields:
            password1 = cleaned_data['password']
            password2 = cleaned_data['repeat_password']

            if len(password1) < 6 or len(password1) > 15:
                raise ValidationError({'password': [_('Password must be \
                                                       between 6 and 15 \
                                                       characters.'), ]})

            if password1 and password2 and password1 != password2:
                raise ValidationError({'repeat_password': [_('Passwords do \
                                                              not match.'), ]})
        return cleaned_data

class SettingsForm(forms.Form):
    start_semester = forms.DateField(
        label=_('Semester Start:'),
        widget=forms.widgets.DateInput(
            attrs={'class': 'datepicker1', 'placeholder': _("mm/dd/yyyy")}))
    end_semester = forms.DateField(
        label=_('Semester End:'),
        widget=forms.widgets.DateInput(
            attrs={'class': 'datepicker1', 'placeholder': _("mm/dd/yyyy")}))

    def clean(self):
        try:
            cleaned_data = super(SettingsForm, self).clean()
            start_semester = cleaned_data.get('start_semester')
            end_semester = cleaned_data.get('end_semester')
            if not (start_semester <= end_semester):
                msg = _('Semester start must be before the end of it.')
                self.add_error('start_semester', msg)
                self.add_error('end_semester', msg)
                raise forms.ValidationError(msg)
        except Exception as e:
            msg = _('Inputs are invalid')
            raise forms.ValidationError(msg)

    def save(self, force_insert=False, force_update=False, commit=True):
        settings = Settings()
        settings.start_semester = self.cleaned_data.get("start_semester")
        settings.end_semester = self.cleaned_data.get("end_semester")
        settings.save()
        return settings

    class Meta:
        model = Settings
        fields = ['start_semester', 'end_semester']

sas/user/views.py
from django.utils.translation import ugettext as _
from django.shortcuts import render, redirect
from .forms import PasswordForm, SettingsForm
from .forms import LoginForm, UserForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib import messages
from sas.views import index
from django.contrib.auth.decorators import login_required
from sas.decorators.decorators import required_to_be_admin
from django.views.generic.edit import FormView
from django.views import View

class NewUserView(FormView):
    template_name = "user/newUser.html"
    form_class = UserForm
    success_url = "/"

    def form_valid(self, form):
        form.insert()
        messages.success(self.request, _('You have been registered'))
        return super(NewUserView, self).form_valid(form)

class EditUserView(View):
    
    def post(self, request):
        user_form = UserForm(request.POST, editing=True,
                             instance=request.user.profile_user)
        if user_form.is_valid():
            useprofile = user_form.update(request.user.profile_user)
            request.user.refresh_from_db()
            messages.success(request, _('Your data has been updated'))
        return self.get(request,user_form=user_form)
            
    def get(self, request, user_form=None):
        if user_form is None:
            user_form = UserForm(instance=request.user.profile_user)
        change_form = PasswordForm()
        return render(request,
                      'user/editUser.html',
                      {'form_user': user_form, 'change_form': change_form})


class LoginView(FormView):
    template_name = "user/newUser.html"
    form_class = LoginForm
    success_url = "/"

    def form_valid(self, form):
        user = form.authenticate_user()
        login(self.request, user)
        return super(LoginView, self).form_valid(form)

    def form_invalid(self, form):
        return index(self.request, login_form=form)

    def get(self, request, *args, **kwargs):
        return redirect('index')


def logout_user(request):
    if hasattr(request, 'user') and isinstance(request.user, User):
        logout(request)
        messages.success(request, _('You have been logged out successfully!'))
    return redirect('index')


def delete_user(request):
    if request.user.is_authenticated():
        request.user.delete()
        logout(request)
        return index(request)
    else:
        return index(request)


class ChangePasswordView(FormView):
    form_class = PasswordForm

    def render_template(self, change_form=PasswordForm()):
        user_form = UserForm(instance=self.request.user.profile_user)
        return render(self.request,
                      'user/editUser.html',
                      {'form_user': user_form, 'change_form': change_form})

    def form_valid(self, form):
        if(form.is_password_valid(self.request.user.username)):
            form.save(self.request.user)
            login(self.request, self.request.user)
            messages.success(self.request,
                             _('Your password has been changed'))
            return self.render_template()
        else:
            return self.render_template(change_form=form)

    def form_invalid(self, form):
        return self.render_template(change_form=form)

    def get(self, request, *args, **kwargs):
        return redirect('index')


@login_required(login_url='/?showLoginModal=yes')
@required_to_be_admin
def search_user(request):
    id = request.user.profile_user.id
    users = UserProfile.objects.all().exclude(pk=id)
    return render(request, 'user/searchUser.html', {'users': users})


@login_required(login_url='/?showLoginModal=yes')
@required_to_be_admin
def make_user_an_admin(request, id):
    try:
        user = UserProfile.objects.get(pk=id)
        if user.is_academic_staff():
            user.user.groups.clear()
            user.make_as_admin()
            messages.success(request, _('User ' + user.full_name() +
                                        ' is now an admin.'))
        else:
            messages.error(request, _('User ' + user.full_name() +
                                      ' is already an admin.'))
    except:
        messages.error(request, _('User not found.'))
    finally:
        return search_user(request)

@login_required(login_url='/?showLoginModal=yes')
@required_to_be_admin
def settings(request):
    if request.method == "POST":
        form = SettingsForm(request.POST)
        if not(form.is_valid()):
            return render(request, 'user/settings.html',
                          {'form_settings': form})
        else:
            form.save()
            messages.success(request, _('Settings updated'))
            return index(request)
    else:
        form = SettingsForm()
        return render(request, 'user/settings.html', {'form_settings': form})

sas/user/templates/user/editUser.html
{% extends 'sas/base.html' %}
{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans "Edit user data" %}{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-xs-8 col-sm-6 col-md-6 col-md-offset-3 col-xs-offset-2 col-sm-offset-3">
      <h1 class="text-center">{% trans "Personal Data" %}</h1>
      <hr class="star-light">
      <div class="form-content">
        <form class="form-horizontal" method = 'POST' action="/user/edituser/">
          {% csrf_token %}
          {% for field in form_user %}
            {% bootstrap_field field exclude="password,repeat_password" %}
          {% endfor %}
          <div>
            <div class="col-xs-12 col-md-6">
              <a id="changepassword" class="btn btn-info btn-block btn-password" href="#change-password"
                  data-toggle="modal">{% trans "Change Password" %}</a>
            </div>
            <div class="col-xs-12 col-md-6">
              {% buttons %}
                  <button class="btn btn-success btn-block btn-edit" type = 'submit'>{% trans "Save Data" %}</button>
              {% endbuttons %}
            </div>
            <div class="col-xs-12 col-md-6">
              <a id="deleteuser" class="btn btn-danger btn-block btn-delete" href="/user/delete" name="delete">
                {% trans "Delete my Account" %}</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="modal fade" role="dialog" id="change-password">
        <div class="modal-dialog">
            <div class="modal-content">
               <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <p class="modal-title" id="myModalLabel">{% trans "Change Password" %}</p>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="modal-col col-xs-12">
                            <form method="POST" action="/user/change/" id="passwordForm">
              					{% csrf_token %}
                                {% bootstrap_form change_form %}
              					 {% bootstrap_form_errors change_form %}
              					 {% buttons %}
									<button class="btn btn-success btn-block btn-edit" type = 'submit'>
                                        {% trans "Change Password" %}</button>
								 {% endbuttons %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}
{% block extrajs %}
	{% if change_form.errors %}
		<script type="text/javascript">
			$(window).load(function(){
				$('#change-password').modal('show');
			});
		</script>
	{% endif %}
{% endblock %}

sas/user/templates/user/newUser.html
{% extends 'sas/base.html' %}

{% load i18n %}
{% load bootstrap3 %}
{% block title %}{% trans "New User" %}{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-xs-8 col-sm-6 col-md-6 col-md-offset-3 col-xs-offset-2 col-sm-offset-3">
        <h1 class="text-center">{% trans "New User" %}</h1>
        <hr class="star-light">
        <div class="form-content">
           <form class="form-horizontal" method = 'POST'>
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button class="btn btn-info btn-block" type = 'submit'>{% trans "Register" %}</button>
                {% endbuttons %}
            </form>
        </div>
      </div>
    </div>
{% endblock %}

sas/user/templates/user/searchUser.html
{% extends 'sas/base.html' %}

{% load i18n user_extras %}
{% load bootstrap3 staticfiles %}
{% bootstrap_messages %}

{% block extrastyle %}
  <link rel="stylesheet" href="{% static "plugins/datatables/jquery.dataTables.css" %}">
  <link rel="stylesheet" href="{% static "plugins/datatables/dataTables.bootstrap.css" %}">
  <link rel="stylesheet" href="{% static "plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" %}">
{% endblock %}

{% block title %}{% trans "Users" %}{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-sm-offset-1">
      <h1 class="text-center">{% trans "Users" %}</h1>
      <hr class="star-light">
      <div>
        <table id="users" class="table table-striped table-bordered " cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Registration Number" %}</th>
                <th>{% trans "Category" %}</th>
                <th>{% trans "Type" %}</th>
                <th class="all">{% trans "Make an Admin" %}</th>
              </tr>
            </thead>
            <tbody>
            {% for user in users %}
              <tr>
                <td>{{ user.full_name }}</td>
                <td>{{ user.registration_number }}</td>
                <td>
                    {{ user|category }}
                </td>
                <td>
                    {{ user|type }}
                </td>
                <td>
                    {% if user.is_academic_staff %}
                    <button class="btn btn-primary" data-href="{% url 'user:usertoadmin' user.id %}"
                        data-toggle="modal" data-target="#modalMakeAnAdmin" id="make-an-admin">
                        <span class="glyphicon glyphicon-user" ></span> {% trans "Make an Admin" %}
                    </button>
                    {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
          <tfoot>
            <tr>
              <th>{% trans "Name" %}</th>
              <th>{% trans "Registration Number" %}</th>
              <th>{% trans "Category" %}</th>
              <th>{% trans "Type" %}</th>
              <th class="all">{% trans "Make an Admin" %}</th>
            </tr>
          </tfoot>
        </table>

          <!-- Modal -->
          <div class="modal fade" id="modalMakeAnAdmin" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="dialog">
              <div class="modal-content">
                <div class="modal-header delete-header">
                  <button class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <p class="modal-title" id="myModalLabel">{% trans "Confirm making user an admin" %}</p>
                </div>
                <div class="modal-body make-user-an-admin-body">
                  <p>{% trans "Are you sure you want to make this user an admin?" %}</p>
                </div>
                <div class="modal-footer make-user-an-admin-footer">
                   <a class="btn btn-primary btn-ok" id="action-make-admin">
                    {% trans "Make an Admin" %}</a>
                  <a class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</a>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block extrajs %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/responsive.bootstrap.min.js' %}"></script>
<!-- page script -->
<script>
$('#modalMakeAnAdmin').on('show.bs.modal', function(e) {
    $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
});
  $(function () {

    var table = $('#users').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "language": {
                "url": "{% static 'plugins/datatables/Portuguese-Brasil.json' %}"
      }
    });

    // Apply the filtering
    table.columns().every( function () {
        var that = this;

        $( 'input', this.footer() ).on( 'keyup change', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );

    new $.fn.dataTable.Responsive(table, {
      details: {
                display: $.fn.dataTable.Responsive.display.modal( {
                    header: function ( row ) {
                        var data = row.data();
                        var closing = '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'
                        return '<h2><i class="fa fa-fw fa-calendar-check-o"></i> Detalhes'+closing+'</h2>';
                    }
                } ),
                renderer: $.fn.dataTable.Responsive.renderer.tableAll( {
                    tableClass: 'table'
                } )
            }
    } );
  });

</script>
{% endblock %}

sas/user/templates/user/settings.html
{% extends 'sas/base.html' %}

{% load i18n %}
{% load bootstrap3 %}
{% load bootstrap3 staticfiles %}
{% block title %}{% trans "New User" %}{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-xs-8 col-sm-6 col-md-6 col-md-offset-3 col-xs-offset-2 col-sm-offset-3">
        <h1 class="text-center">{% trans "Settings" %}</h1>
        <hr class="star-light">
        <div class="form-content">
           <form class="form-horizontal" method = 'POST'>
                {% csrf_token %}
                {% bootstrap_form form_settings %}
                {% buttons %}
                    <button class="btn btn-info btn-block" type = 'submit'>{% trans "Register" %}</button>
                {% endbuttons %}
            </form>
        </div>
      </div>
    </div>
{% endblock %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'jquery/ui/jquery-ui.min.css' %}" />
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(document).ready(function () {

  $('.datepicker1').datepicker({
			inline: true,
			useCurrent: true,
			autoclose: true,
	});

    $.datepicker.setDefaults( $.datepicker.regional[ "{{ LANGUAGE_CODE|default:"" }}" ] )
});
</script>
<script src= "{% static 'jquery/ui/datepicker-pt-BR.js' %}"></script>
<script src= "{% static 'jquery/ui/jquery-ui.min.js' %}"></script>
{% endblock %}